services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0.18
    container_name: cubesat-mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped
